# Generated by Django 4.1.7 on 2023-03-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apoth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='photo',
            field=models.ImageField(blank=bool, upload_to=''),
        ),
    ]
